apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 4000
  selector:
    app: {{ .Chart.Name }}
  type: ClusterIP