docker:
  image:
    name: app-backend
    version: development
deployment:
  replicas: 1
  container:
    port: 4000
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi